### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by link858** [Stonemercy/BOB-E#1]
### Hey bud id really like to use your bot
I am getting an error when trying to run the bot. I made a config.json with
```
{ "token": "xx", 
"clientId": "xx", 
"steamKey": "xx"}
```

  im not sure what all the variables are you want here but thats just what I seen referenced.
  but after I install the modules with `npm install` I use `node index.js` to start the bot and I get this error
  

```
node:internal/process/promises:265
triggerUncaughtException(err, true /* fromPromise */);
^

Error
at Database.<anonymous> (C:\beastbot\node_modules\sequelize\lib\dialects\sqlite\query.js:179:27)
at C:\beastbot\node_modules\sequelize\lib\dialects\sqlite\query.js:177:50
at new Promise (<anonymous>)
at Query.run (C:\beastbot\node_modules\sequelize\lib\dialects\sqlite\query.js:177:12)
at C:\beastbot\node_modules\sequelize\lib\sequelize.js:313:28
at async SQLiteQueryInterface.rawSelect (C:\beastbot\node_modules\sequelize\lib\dialects\abstract\query-interface.js:423:18)
at async Function.aggregate (C:\beastbot\node_modules\sequelize\lib\model.js:1250:19)
at async Function.count (C:\beastbot\node_modules\sequelize\lib\model.js:1273:20)
at async Object.execute (C:\beastbot\events\ready.js:9:22) {
name: 'SequelizeDatabaseError',
parent: [Error: SQLITE_ERROR: no such table: users] {
errno: 1,
code: 'SQLITE_ERROR',
sql: 'SELECT count(*) AS `count` FROM `users` AS `users`;'
},
original: [Error: SQLITE_ERROR: no such table: users] {
errno: 1,
code: 'SQLITE_ERROR',
sql: 'SELECT count(*) AS `count` FROM `users` AS `users`;'
},
sql: 'SELECT count(*) AS `count` FROM `users` AS `users`;',
parameters: {}
}
```

**I can edit the `currencyShop.sqlite` db and add a table called `users` and then run the bot again and it will spit out a different code about missing a column called `steam_id`**
The sql db is blank, is it supposed to be?
Im probably doing something wrong on my end. Do you have any ideas?

**Comment by Stonemercy** [comment]
Hi!

First of all, glad you want to use my bot, I think you're the first to do so 😄 

If you would like to use it, I have it hosted already, the invite link is:

https://discord.com/api/oauth2/authorize?client_id=885273480449380352&permissions=139586948288&scope=bot%20applications.commands

I only really uploaded onto github for open-source-ness and version handling, but I planned to host the bot myself

If you have any more issues, please do let me know!

**Comment by Stonemercy** [comment]
Issue sorted
